name: money_jars
description: 一个美观实用的记账Web应用，采用存钱罐概念管理个人财务
homepage: https://github.com/BrunonXU/MoneyJars
repository: https://github.com/BrunonXU/MoneyJars
license: Proprietary

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # UI组件
  cupertino_icons: ^1.0.2
  
  # 状态管理
  provider: ^6.0.5
  
  # 数据存储 - Hive高性能本地数据库
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2  # Web平台localStorage封装
  path: ^1.8.3
  
  # 图表可视化
  fl_chart: ^1.0.0
  
  # 动画和UI增强
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1
  
  # 屏幕适配
  flutter_screenutil: ^5.9.0
  
  # 工具库
  intl: ^0.20.2
  uuid: ^4.1.0
  
  # 依赖注入
  get_it: ^8.0.3
  
  # 值对象比较
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  
  # Hive代码生成
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # 图标和图片
  assets:
    - assets/images/red_knitted_jar.png
    - assets/images/green_knitted_jar.png
    - assets/images/piggy_bank.png  # 小猪图像（综合罐头）
    - assets/images/festive_piggy_bank.png  # 节日小猪图像
    - assets/images/icons-1.png  # 设置按钮图标
    - assets/icons/v0-fargo-green-final.png
    - assets/icons/V0-fargo-jar-final.png
    - assets/icons/v0-fargo-jar-big.svg
    - assets/icons/ICON.png 